name: Expo Android Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with Expo
        run: eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Decode Google Play Service Account
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > google-play-service.json

      - name: Build App Bundle
        run: eas build -p android --profile production --non-interactive

      - name: Submit to Play Store
        run: eas submit -p android --profile production --non-interactive
